name: Build
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          path: _build

      - name: Remove build folder
        run: rm -rf _build
        working-directory: /home/ubuntu/actions-runner
          
      - name: Move build folder
        run: mv $GITHUB_WORKSPACE/_build /home/ubuntu/actions-runner/

      - name: Build Spring application
        run: mvn package
        working-directory: /home/ubuntu/actions-runner/_build/server
