name: Build
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
    defaults:
      run:
        shell: bash
        working-directory: ./server
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          path: _build

      #Set up java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Spring application
        run: mvn package
