name: Build
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          path: _build
          
      - name: Move build folder
        run: mv $GITHUB_WORKSPACE/_build /home/ubuntu/actions-runner/

      #Set up java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Spring application
        working-directory: /home/ubuntu/actions-runner/_build/server
        run: mvn package
