name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
    defaults:
      run:
        shell: bash
        working-directory: ./server
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Stop current execution
      run: sudo kill -9 `sudo lsof -t -i:8080`
        
    - name: Build with Maven
      run: mvn package
      
    - name: Execute Jar file
      run: sudo java -jar /home/ubuntu/actions-runner/_work/JBE/JBE/server/target/server.jar &
