name: "Deploy Bean database"

on: [pull_request, workflow_dispatch]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  infra:
    runs-on: ubuntu-latest
    env:

    defaults:
      run:
        shell: bash

    steps:
