name: Spring Deployment
on: 
  workflow_run:
    workflows: [ "Terraform" ]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./server
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      #Set up java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Spring application
        run: mvn package -D spring

      # Deploy to EC2 instance
      - name: Deploy to EC2 (SCP)
        run: |
          scp -o StrictHostKeyChecking=no -i "${{ secrets.PRIVATE_KEY }}" "target/server.jar" ubuntu@${{ secrets.WEB_PUBLIC_DNS }}:jbe/
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.PRIVATE_KEY }}" ubuntu@${{ secrets.WEB_PUBLIC_DNS }}
          sudo kill -9 `sudo lsof -t -i:80` & sudo java -jar /jbe/server.jar &