name: "Spring Deployment"
on: 
  workflow_run:
    workflows: [ Terraform ]
    types: [ completed ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./server
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      # Configure Maven and build Spring application
      - name: Set up Maven
        uses: maven/maven-action@v3
        with:
          maven: 3.9.x

      - name: Build Spring application
        run: mvn package -D spring

      # Deploy to EC2 instance
      - name: Deploy to EC2 (SCP)
        run: |
          scp -o StrictHostKeyChecking=no -i "${{ secrets.PRIVATE_KEY }}" "target/server.jar" ubuntu@${{ secrets.WEB_PUBLIC_DNS }}:jbe/
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.PRIVATE_KEY }}" ubuntu@${{ secrets.WEB_PUBLIC_DNS }}
          sudo kill -9 `sudo lsof -t -i:80` & sudo java -jar /jbe/server.jar &